default:
  image: node:18.16.0-alpine 

stages:
  - build
  - unit
  - api
  - ui
  - bdd

build:
  stage: build
  script:
    - npm install

unit:
  stage: unit
  script:
    - npm install mocha
    - npm install mochawesome --save-dev  
    - npm run test

api:
  stage: api
  script:
    - npm install mocha
    - npm install mochawesome --save-dev
    - npm install axios
    - npm --prefix api run test

ui:
  stage: ui
  script:
    - npm install mocha
    - npm install mochawesome --save-dev
    - npm --prefix wdio run wdio

bdd:
  stage: bdd
  script:
    - npm install mocha
    - npm install mochawesome --save-dev
    - npm --prefix bdd run wdio   

# post_build:
#   stage: .post
#   script: 
#     - mocha --reporter mochawesome --reporter-options mochaFile=junit.xml
#   artifacts:
#     when: always
#     paths:
#       - mochawesome-report/mochawesome.html
#     reports:
#       junit: report/*.xml