default:
  image: node:18.16.0-alpine 

stages:
  - build
  - unit
  - api
  - ui
  - bdd

before_script: 
  - apk add --no-cache sudo curl build-base g++ libpng libpng-dev jpeg-dev pango-dev cairo-dev giflib-dev python3 firefox

build:
  stage: build
  script:
    - npm install

unit:
  stage: unit
  script:
    - npm install mocha
    - npm install mochawesome --save-dev  
    - npm run test
  artifacts:
    paths:
      - mochawesome-report/  
    expire_in: 3 days
    when: always   

api:
  stage: api
  script:
    - npm install mocha
    - npm install mochawesome --save-dev
    - npm --prefix api install axios
    - npm --prefix api run test
  artifacts:
    paths:
      - api/mochawesome-report/  
    expire_in: 3 days
    when: always  

# ui:
#   stage: ui
#   script:
#     - npm install mocha
#     - npm install mochawesome --save-dev
#     - npm --prefix wdio install wdio
#     - npm --prefix wdio install chromedriver
#     - npm --prefix wdio run wdio
#     artifacts:
#       paths:
#        - wdio/allure-report/  
#      expire_in: 3 days
#      when: always


bdd:
  stage: bdd
  services:
    - selenium/standalone-chrome
  script:
    - npm install mocha
    - npm install mochawesome --save-dev
    - npm --prefix bdd install webdriverio
    - npm --prefix bdd install chromedriver
    - npm --prefix bdd run wdio
