default:
  image: node:18.16.0-alpine 

stages:
  - build
  - unit

build:
  stage: build
  script:
    - npm install

unit:
  stage: unit
  script:
    - npm install --global mocha
    - npm install --global mochawesome --save-dev  
    - npm run test

post_build:
  stage: .post
  script: 
    - mocha --reporter mochawesome --reporter-options mochaFile=junit.xml
  artifacts:
    when: always
    paths:
      - 'mochawesome-report/mochawesome.html'
    reports:
      junit: 'report/*.xml'