default:
  image: node:18.16.0-alpine 

stages:
  - build
  - unit

build:
  stage: build
  script:
    - npm install

unit:
  stage: unit
  script:
    - npm install --global mocha
    - npm run test

post_build:
  stage: .post
  script:
    - mocha --reporter mocha-junit-reporter --reporter-options mochaFile=junit.xml
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml